[build]
  base = "/"
  publish = "dist/"
  command = "npm run build"

[[redirects]]
  from = "https://junickim.me/*"
  to = "https://junic.kim/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.junickim.me/*"
  to = "https://junic.kim/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "/ko/"
  status = 302
  conditions = { Language = ["ko"], }

[[redirects]]
  from = "/"
  to = "/en/"
  status = 302

[[redirects]]
  from = "/:page"
  to = "/en/:page"
  status = 302
