[build]
  base = "/"
  publish = "dist/"
  command = "npm run build"

[[redirects]]
  from = "https://junickim.me/*"
  to = "https://junic.kim/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.junickim.me/*"
  to = "https://junic.kim/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://junic.kim/"
  to = "https://junic.kim/ko/"
  status = 302
  conditions = { Language = ["ko"] }

[[redirects]]
  from = "https://junic.kim/"
  to = "https://junic.kim/en/"
  status = 302

[[redirects]]
  from = "https://junic.kim/:page"
  to = "https://junic.kim/en/:page"
  status = 302
